In [71]:
import numpy as np
import matplotlib.pyplot as plt

In [84]:
# Step 1 Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])
plt.scatter(x[0], x[1])
plt.show()

In [73]:
print x

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [74]:
print y 

[[0]
 [1]
 [1]
 [0]]


In [75]:
#Step 2 build model

num_epochs = 200000
plot_error = []

#initialize weights
np.random.seed(7)
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [76]:
print syn0

[[ -8.47383421e-01   5.59837584e-01  -1.23181537e-01   4.46930356e-01]
 [  9.55979024e-01   7.69917408e-02   2.24092732e-03  -8.55897733e-01]
 [ -4.63122040e-01  -2.34998349e-04   3.58459992e-01   6.07478072e-01]]


In [77]:
print syn1

[[-0.23811773]
 [-0.86812731]
 [-0.4237088 ]
 [ 0.81918706]]


In [78]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

In [79]:
#Step 3 Train Model

for j in xrange(num_epochs):
    #feed forward through layers 0,1, and 2
    k0 = x
    k1 = nonlin(np.dot(k0, syn0))
    k2 = nonlin(np.dot(k1, syn1))
    
    #how much did we miss the target value?
    k2_error = y - k2
    
    if (j% 10000) == 0:
        plot_error.append(np.mean(np.abs(k2_error)))
        print "Error:" + str(np.mean(np.abs(k2_error)))
    
    #in what direction is the target value?
    k2_delta = k2_error*nonlin(k2, deriv=True)
    
    #how much did each k1 value contribute to k2 error
    k1_error = k2_delta.dot(syn1.T)
    
    k1_delta= k1_error * nonlin(k1,deriv=True)
    
    syn1 += k1.T.dot(k2_delta)
    syn0 += k0.T.dot(k1_delta)

plt.plot(plot_error)
plt.show()

Error:0.501362713079
Error:0.00976387487092
Error:0.00670766367985
Error:0.00540927072394
Error:0.00465006419062
Error:0.00413805323714
Error:0.00376321083889
Error:0.00347368600743
Error:0.00324144706236
Error:0.00304984839146
Error:0.00288830449826
Error:0.00274972181471
Error:0.00262914596761
Error:0.0025229985979
Error:0.00242862241285
Error:0.0023439974379
Error:0.00226755722229
Error:0.00219806590069
Error:0.00213453365519
Error:0.00207615716779
